### ISSUE TITLE
Program Detected as Virus When Ran

### ISSUE THREAD

**Issue by sdphadke** [brickineers/MelodyMapper#1]
Hello, 

The app isn't working because windows Is giving me a message saying that it was unrecognized so they went on the safe side and blocked olpening it. Btw I am not using my own antivirus it's windows predownloaded antivirus.

- Rohit Aute (rohitaute80@gmail.com)

Submitted by sdphadke

**Comment by braban** [comment]
This is not an issue, the problem isn’t windows detecting it as a virus, it is just an unrecognized program so windows is just letting you know.
